##################guns配置####################
guns:
  muti-datasource-open: true #是否开启多数据源(true/false)
##################spring配置############################
server:
  port: 8091
spring:
  aop:
    proxy-target-class: false #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/test?serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    db-name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    password: test_123456
    timeout: 5000
    pool:
      max-idle: 8
      max-wait: -1
#多数据源
test:
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/yongli_database?serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    db-name: yongli_database
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/example/demo_activity/test1/dao/mapping/*.xml
  type-aliases-package: com/example/demo_activity/test1/model


