##################guns配置####################
guns:
  muti-datasource-open: true #是否开启多数据源(true/false)
##################spring配置############################
########工作流配置##########
flowable:
  check-process-definitions: false #flowable自动部署的设置
  #database-schema-update: true
server:
  port: 8091
spring:
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    #username: root
    #password: 123456
    #db-name: test
    url: jdbc:mysql://49.232.161.254:3306/test?serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: liyong123456
    db-name: test
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    #host: 127.0.0.1
    host: 49.232.161.254
    port: 6379
    database: 5
    # redis暂时没有密码
    #password: test_123456
    #阿里云的redis密码
    password: root
    timeout: 5000
    pool:
      max-idle: 8
      max-wait: -1
#文件上传限制
  http:
    multipart:
      max-file-size: 500MB   #单个文件大小
      max-request-size: 2000MB #总上传的数据大小
#阿里云上传


#多数据源
test:
  datasource:
    url: jdbc:mysql://49.232.161.254:3306/yongli_database?serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: liyong123456
    db-name: yongli_database
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/example/demo_activity/test1/dao/mapping/*.xml
  type-aliases-package: com/example/demo_activity/test1/model
  global-config:
    id-type: 1  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    callSettersOnNulls: true #Mybatis查询数据库空字段不返回
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用



